# These are supported funding model platforms

patreon: https://www.patreon.com/sodacamper
open_collective: https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository
custom: ['https://opendata.ch/organisation/spenden/']
