# These are supported funding model platforms

patreon: https://www.patreon.com/sodacamper
open_collective: https://opencollective.com/dat-alets-ch
custom: ['https://opendata.ch/organisation/spenden/']
